<ListItemWithCheckbox>:

    IconLeftWidget:
        icon: root.icon

    RightCheckbox:


Screen:
    	
    ScrollView:

        MDList:
            id: scroll
          
 
    MDRaisedButton:
        id:CBbut
        pos_hint:{"center_x": 0.5, "center_y": 0.5}
        increment_width: "75dp"
        text:"CBuilder"
        
    MDFloatingActionButtonSpeedDial:
        data: app.data
        rotation_root_button: True